### ISSUE TITLE
Cross vault links show as "(Private)"

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron-site#370]
I guess this is the same issue I reported [on dendron-docs](https://github.com/dendronhq/dendron-docs/issues/10).

## Example

This is the markdown:

    Check out an end-to-end workstyle, managing 20k notes, using schemas and daily journals from [[A Day in Dendron|dendron://dendron.dendron-site/community.greenhouse.2021-07-23-using-dendron-with-20k-notes]]

This is what gets rendered:

> Check out an end-to-end workstyle, managing 20k notes, using schemas and daily journals from A Day in Dendron (Private)

**Comment by ScriptAutomate** [comment]
Ah, thanks for the catch! In this case, this is because the link on `dendron-site` was broken. Fix will be included in docs public update on Friday (2022-02-18).

This is different from the `dendron-docs` issue, which I will respond to in that repo.

Commit: https://github.com/dendronhq/dendron-site/commit/850fe88e42cf775a31d19ce5b7865090e93e0f1a
