### ISSUE TITLE
css edit link points to documentation that doesn't exists anymore

### ISSUE THREAD

**Issue by 13013SwagR** [dendronhq/dendron-site#383]
The following [line](https://github.com/dendronhq/dendron-site/blob/36f2c9a65e6965b4b0a2df35572eacf883a32b65/vault/dendron.guides.tips.md?plain=1#L52) points to documentation that doesn't exists anymore.
The anchor `#can-i-customize-the-markdown-preview-css` seems to no longer exist.

**Comment by ScriptAutomate** [comment]
Thank you for pointing this out!

These directions were associated with the old preview and publishing tools, which we have since migrated off of. I have updated our docs, which will go live on Friday:
- https://github.com/dendronhq/dendron-site/commit/52920a820b4fe89f0a4ebd5534713d4392bc6a9a

## Still interested in customizations?

When it comes to the future of CSS and customizations of Dendron Preview and Publishing output, we have a discussion on an RFC. Feel free to provide feedback:
- https://github.com/dendronhq/dendron/discussions/1298

A few issues are also open in the `dendron` repo related to wanting to use custom CSS. Here is one issue with links included in the comments to some other related issues:
- https://github.com/dendronhq/dendron/issues/1360

**Comment by 13013SwagR** [comment]
Thanks, will check that out.
