### ISSUE TITLE
No live Graph View on dendron-site

### ISSUE THREAD

**Issue by immartian** [dendronhq/dendron-site#395]
Is it possible to show interactive Graph View on dendron's public site? 

I understand there's a discussion https://github.com/dendronhq/dendron/discussions/615 around this topic, but there could be something easily borrowed from D3.js https://observablehq.com/@d3/force-directed-graph.

**Comment by gulprun** [comment]
I guess this one is more coherent to Dendron's purpose:

https://observablehq.com/@icarofonseca/design-theory-mindmap

![image](https://user-images.githubusercontent.com/33362680/152761174-47448ddb-a4dc-4a34-a7dc-5a515be95e34.png)

**Comment by ScriptAutomate** [comment]
When it comes to graph rework improvements, that discussion is the perfect place to add comments on the future of how graph view may continue to be implemented and capable of embedding.

I've added a comment with your suggested resource links here:
- https://github.com/dendronhq/dendron/discussions/615#discussioncomment-2192455

Feel free to add additional information in response to that discussion comment, or add new comments to the discussion. We value community feedback on how the implementation can be done! :)

Since issues in this repo are meant for the wiki/docs for Dendron, rather then Dendron features/enhancements (which can be raised at https://github.com/dendronhq/dendron), I'll be closing this issue.
